### PR TITLE
Fix attendance so it does not use user.smallgroup

### LINKED ISSUE #257: Users can be in multiple small groups, but can only see one

### LINKED ISSUE #465: Small Group Attendance Calculator
Looks like there is a bug in small group attendance. Got this screenshot from Theo Rice. Looks like it is counting last semester attendance on the profile.

image

### LINKED ISSUE #483: Users that are in two small groups cannot attend the first one.
Possibly related to #257 

@seveibar I went to early/normal session (Sage 3713) instead of #latesession today btw.

### PR DESCRIPTION
**Pull request by kmcnellis**
Fixes #483
fixes #257
Should fix #465

### CODE REVIEW

File: client/app/smallgroup/smallgroup.controller.js [hunk 1]
```diff
@@ -10,24 +10,18 @@ angular.module('observatory3App')
...
     callback = callback || function () {};
-
-    if (!$scope.user.smallgroup){
-      $scope.loaded = true;
-      $scope.smallgroup = null;
-      return;
-    }
-
-    $http.get('/api/smallgroup/' + $scope.user.smallgroup).success(function (smallgroup) {
+    return User.smallgroup({id:$scope.user._id})
```
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: did you get this working? You were asking about this before

File: client/app/smallgroup/smallgroup.controller.js [hunk 2]
```diff
@@ -10,24 +10,18 @@ angular.module('observatory3App')
...
+    .$promise.then(function(smallgroup){
       $scope.smallgroup = smallgroup;
       $scope.loaded = true;
-      if (!smallgroup) {
+      if (!$scope.smallgroup._id) {
         $scope.smallgroup = false;
```
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: any reason this is a boolean? why not null?

File: client/app/smallgroup/smallgroup.controller.js [hunk 3]
```diff
@@ -10,24 +10,18 @@ angular.module('observatory3App')
...
         return false;
       }
       if ('dayCode' in smallgroup && smallgroup.dayCode) {
         $scope.dayCode = smallgroup.dayCode;
       }
-      $http.get('/api/smallgroup/' + $scope.user.smallgroup + '/members').success(function (members) {
+      return $http.get('/api/smallgroup/' + $scope.smallgroup._id + '/members').success(function (members) {
```
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: do we have a factory for this yet?

File: client/app/smallgroup/smallgroup.controller.js [hunk 4]
```diff
@@ -90,7 +83,7 @@ angular.module('observatory3App')
 
   $scope.saveSmallGroupName = function () {
     $scope.edittingSmallGroupName = false;
-    $http.put("/api/smallgroup/" + $scope.user.smallgroup + "/name", {
+    $http.put("/api/smallgroup/" + $scope.smallgroup + "/name", {
```
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: `$scope.smallgroup._id` since it's not the user attribute that is an id?

File: client/app/smallgroup/smallgroup.controller.js [hunk 5]
```diff
@@ -115,13 +107,12 @@ angular.module('observatory3App')
   };
 
   var submitDayCode = function(code){
-      var user = Auth.getCurrentUser();
       $http.post('/api/attendance/attend', {
         dayCode: code
-      }).success(function(info){
+      }).success(function(){
```
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: ignoring the response from the API? things get sent back like "Please verify" do they not?

File: server/api/attendance/attendance.controller.js [hunk 6]
```diff
@@ -335,17 +335,13 @@ exports.attend = function(req,res){
...
-        if (!user.smallgroup || user.smallgroup === undefined || user.smallgroup === null){
-          return res.send(400, 'No small group found/incorrect daycode!');
-        }
-
-        return SmallGroup.findById(user.smallgroup, function(err, smallgroup){
+        return SmallGroup.findOne({"students":user._id, "classYear":classYear._id}, function(err, smallgroup){
           if (err) {return handleError(err)}
           // if the user has no smallgroup, they cannont submit smallgroup  attendance
-          if (!smallgroup){return res.send(400, 'Incorrect day code');}
+          if (!smallgroup){return res.send(400, 'No small group found or incorrect daycode!');}
```
Comment (agundy) [inline server/api/attendance/attendance.controller.js]: i think we are autoadding users to the smallgroup if they aren't part of one and they submit the right daycode. So Incorrect Daycode should be the message shouldn't it?

File: server/api/attendance/attendance.controller.js [hunk 7]
```diff
@@ -335,17 +335,13 @@ exports.attend = function(req,res){
...
+
           // Small group, and not a bonus day
-          else if (smallgroup.dayCode === code){
+          if (smallgroup.dayCode === code){
```
Comment (agundy) [inline server/api/attendance/attendance.controller.js]: reasoning for doing this? This changes expected behavior

File: server/api/project/project.controller.js [hunk 8]
```diff
@@ -38,7 +38,6 @@ exports.stats = function(req, res) {
       ],
       function(err, results){
         if (err) {
-          console.log(err);
```
Comment (agundy) [inline server/api/project/project.controller.js]: we should log errors shouldn't we? Maybe not to the console but somewhere

File: server/api/user/user.controller.js [hunk 9]
```diff
@@ -60,7 +60,6 @@ exports.publicStats = function(req, res) {
       ],
       function(err, results){
         if (err) {
-          console.log(err);
```
Comment (agundy) [inline server/api/user/user.controller.js]: api should log failures somewhere

File: server/api/user/user.controller.js [hunk 10]
```diff
@@ -245,9 +244,7 @@ exports.show = function (req, res, next) {
     if (err) {return next(err);}
     if (!user) {return res.send(404);}
     var profile = user.profile;
-    ClassYear.getCurrent(function (err, classYear) {
```
Comment (agundy) [inline server/api/user/user.controller.js]: weirddd why did we ever do this?

File: server/config/seed.js [hunk 11]
```diff
@@ -23,15 +23,18 @@ var Project = require('../api/project/project.model');
 var Post = require('../api/post/post.model');
 var Smallgroup = require('../api/smallgroup/smallgroup.model');
 var ClassYear = require('../api/classyear/classyear.model')
+var Attendance = require('../api/attendance/attendance.model')
 
 
 // Seed the database with the original sample data
-var seed = function() {
+var seed = function(cb) {
```
Comment (agundy) [inline server/config/seed.js]: I think seve changed this for a reason. @seveibar is this true?

File: server/config/seed/projects.json [hunk 12]
```diff
@@ -15,7 +15,7 @@
     "githubProjectName": "yacs"
 },
 {
-    "_id": "5738cebdffd7ec3b75f3349b",
+    "_id": "000000000000000000000010",
```
Comment (agundy) [inline server/config/seed/projects.json]: doesn't seem necessary?

File: server/config/environment/development.js [hunk 13]
```diff
@@ -17,5 +17,5 @@ module.exports = {
   // For testing verification
   // attendanceVerificationRatio: 1,
 
-  seedDB: true
+  seedDB: false
```
Comment (kmcnellis) [inline server/config/environment/development.js]: Yup. I thought we had false as the default since the grunt seed command was created. It must have gotten switched at some point.

File: server/api/user/user.controller.js (hunk 10 above)
Comment (kmcnellis) [inline server/api/user/user.controller.js]: Not really sure..

File: client/app/smallgroup/smallgroup.controller.js (hunk 1 above)
Comment (kmcnellis) [inline client/app/smallgroup/smallgroup.controller.js]: Yes, this works

File: client/app/smallgroup/smallgroup.controller.js (hunk 2 above)
Comment (kmcnellis) [inline client/app/smallgroup/smallgroup.controller.js]: No particular reason, but this is the way it was before, and ensures that the front-end treats it correctly

File: client/app/smallgroup/smallgroup.controller.js (hunk 1 above)
Comment (agundy) [inline client/app/smallgroup/smallgroup.controller.js]: :+1:

File: client/app/smallgroup/smallgroup.controller.js (hunk 5 above)
Comment (kmcnellis) [inline client/app/smallgroup/smallgroup.controller.js]: This is no different from the original code. Small groups do not currently require verification

File: server/api/attendance/attendance.controller.js (hunk 6 above)
Comment (kmcnellis) [inline server/api/attendance/attendance.controller.js]: We are not yet doing that. That is a future issue.

File: server/api/attendance/attendance.controller.js (hunk 7 above)
Comment (kmcnellis) [inline server/api/attendance/attendance.controller.js]: It does not change the behavior. The previous if returns if true.

File: server/api/project/project.controller.js (hunk 8 above)
Comment (kmcnellis) [inline server/api/project/project.controller.js]: That would be a different issue

File: server/config/seed/projects.json (hunk 12 above)
Comment (kmcnellis) [inline server/config/seed/projects.json]: It is - makes it much easier to write and verify tests

File: client/app/smallgroup/smallgroup.controller.js (hunk 4 above)
Comment (kmcnellis) [inline client/app/smallgroup/smallgroup.controller.js]: fixed

File: server/config/seed.js (hunk 11 above)
Comment (kmcnellis) [inline server/config/seed.js]: I just tried this without cb and the test failed

**Comment by kmcnellis** [comment]
@agundy Not really sure why the test is failing. It works locally for me. Could you check it out?

File: server/config/seed.js (hunk 11 above)
Comment (seveibar) [inline server/config/seed.js]: this function should return a promise and should not have a callback- this is the new javascript paradigm

Comment (kmcnellis) [inline server/config/seed.js]: I already changed it back. Not sure why github doesn't update the snippets anymore.

**Comment by agundy** [comment]
Not sure why it's sending a 400. Failed once for me the second time I ran it. But hasn't failed again. Maybe a flakey test?

**Comment by kmcnellis** [comment]
It should work now @agundy

**Comment by agundy** [comment]
:shipit:
