### PR TITLE
Blog fixes

### LINKED ISSUE #311: Blog post deletion and edits are not working properly
A normal user receives an error when trying to delete or edit a blog post, saying it cannot be done.  However, an admin can.

### PR DESCRIPTION
**Pull request by zlalvani**
closes #311

### CODE REVIEW

File: client/app/projects/blog/blog.controller.js [hunk 1]
```diff
@@ -19,6 +19,11 @@ angular.module('observatory3App')
         return $scope.isAuthor;
     };
 
+    $scope.userOwnsPost = function(post) {
```
Comment (seveibar) [inline client/app/projects/blog/blog.controller.js]: I don't love the name- admins don't "own" the post ;)

**Comment by seveibar** [comment]
great work zaran
