### PR TITLE
Fix Adding attendance

### LINKED ISSUE #572: Adding attendance from Admin page adds attendance for wrong date
I attempted to add attendance for myself for 1/27/2017, but it added for 1/26/2017 instead. 

Steps to reproduce: 

- Go to Admin -> users
- Choose a user (ex: Brian Kelley)
- Click the add attendance button
- Choose date. I tested with regular day attendance.
- Submit
- Go to "Attend" page, see the shown for attendance is the day before the one chosen.

### PR DESCRIPTION
**Pull request by kmcnellis**
Changed how we handle dates
Fixes #572

### CODE REVIEW

**Comment by kmcnellis** [comment]
Check it out at https://staging.rcos.io !

File: client/components/addAttendance/addAttendance.directive.js [hunk 1]
```diff
@@ -40,15 +40,16 @@ angular.module('observatory3App')
 
     var params = {};
     params.date = $scope.attend.date;
-    params.smallgroup = $scope.attend.type == "Small Group" || $scope.attend.type == "Small Group Bonus Day";
-    params.bonusday = $scope.attend.type == "Bonus Day" || $scope.attend.type == "Small Group Bonus Day";
+    console.log("$scope.attend.date;",$scope.attend.date)
```
Comment (yongabyte) [inline client/components/addAttendance/addAttendance.directive.js]: remove console.log

**Comment by kmcnellis** [comment]
Oops, fixed
